# Adapted from the following post:
# https://medium.com/swlh/publish-a-static-website-in-a-day-with-mkdocs-and-netlify-3cc076d0efaf

[build]
publish = "site"
command = """
pip3 install --upgrade pip
pip3 install -r requirements.txt &&
mkdocs build -d site
"""

[[redirects]]
  from = "https://oras.land/oras-go/"
  to = "github.com/oras-project/oras-go"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"